### ISSUE TITLE
SVG Icons Not Changing Colour

### ISSUE THREAD

**Issue by SmolSoftBoi** [glyphish/color-changer#10]
My SVG icons are not changing colour, they are the original downloads in black.

It creates new copies, but the new copies are essentially just duplicates.

I am using the "701-location-selected-selected@2x.svg" range of files.

Perhaps this a problem with the ~@2x.svg range of files?

**Comment by jpwain** [comment]
@ruddfawcett Any thoughts on how we might debug further to find a cause?

**Comment by ruddfawcett** [comment]
@jpwain @EpicKris the way the SVG conversion works is a bit hacky and incomplete.

Basically I'm searching for a black hexadecimal  in the contents of the SVG and replacing it with `fill=hex`, which should theoretically be XML for fill this object with this color.  It's quite low level and barebones.

In terms of getting a fix, I will definitely rewrite it (it currently only allows conversion from original @jpwain releases, as it scans specifically for `#000000`).

Unfortunately I will not be able to do this for a few days.

However, I will see if I can offer a lower level fix in the meantime, specifically for those icons, and any others that require it (some icons are in slightly different SVG schemes).  I'll try to have this happen tomorrow afternoon.
