### ISSUE TITLE
Doesn't work with @2x pngs

### ISSUE THREAD

**Issue by pupasani** [glyphish/color-changer#2]
Image size ends up half of what I need

**Comment by ruddfawcett** [comment]
Thanks for the report - I'll look into this now.

**Comment by pupasani** [comment]
Actually I was able to get it to work by renaming the icon to take out the @2x suffix. Some reason it halves the size otherwise.

**Comment by ruddfawcett** [comment]
@pupasani Alright, thanks for the additional information and temporary fix.  I'm opening the project now.

**Comment by ruddfawcett** [comment]
Just fixed this bug.  This actually was an interesting problem (one that I had not anticipated), which is that when loading an image with NSImage, using `initWithContentsOfFile:`, the image is processed as a retina image would be processed on iOS, which is to say that the pixel count was halved, as OS X took away the 2x scale.  

On iOS, this could be solved by using UIImage's `scale` property, but unfortunately there is no such property on NSImage, so I stumbled upon the solution, which is to convert the image to NSData, and then use it with `initWithData:`.

``` obj-c
NSData *imageData = [[NSData alloc] initWithContentsOfFile:path];
NSImage *originalImage = [[NSImage alloc] initWithData:imageData];
```

Which can be found here: http://stackoverflow.com/a/15013386

**Comment by pupasani** [comment]
Thanks that fixed it, yes! Very useful app btw, saved me a lot of time.

**Comment by ruddfawcett** [comment]
Great, I'm glad it worked and thanks for the report.  Also glad you enjoy the app!

**Comment by ruddfawcett** [comment]
@pupasani [Version 1.0 (Beta 2)](https://github.com/glyphish/color-changer/releases/tag/v1.0-beta.2) was just released.
