### ISSUE TITLE
doesn't handle @2x images correctly

### ISSUE THREAD

**Issue by ConfusedVorlon** [glyphish/color-changer#3]
1) drag an @2x image to the changer
(1241-play-selected@2x)
the png size is 56*56 pixels
2) select an output location

expected:
output file is 56*56

actual
output file is 28*28

I'm running on mavericks - presumably the image loader is taking the @2x to indicate double density, and the code is re-saving at the size, rather than the pixel dimensions.

**Comment by ruddfawcett** [comment]
Hi @ConfusedVorlon, please see #2, and try building from the project, rather than opening the binary.  Thanks!

**Comment by ConfusedVorlon** [comment]
got it - perhaps note this in 'known issues' until there is a release?

**Comment by ruddfawcett** [comment]
@ConfusedVorlon [Version 1.0 (Beta 2)](https://github.com/glyphish/color-changer/releases/tag/v1.0-beta.2) was just released.
