### ISSUE TITLE
Dimensions changing on output image

### ISSUE THREAD

**Issue by dannycabrera** [glyphish/color-changer#9]
Hey Guys,

If I drop a 1x 28x28 Glyphish icon the output is 56x56. Same applies to @2x (in 56x56 - out 112x112) and @3x (in 84x84 - out 168x168). Shouldn't the output image contain the same dimensions as the source image? This is happening on v1.0 (Beta 2).

Thanks,
DannyC

**Comment by ruddfawcett** [comment]
@dannycabrera thanks for the report!  This should have been closed by #6, but that was before the @3x update.  I'll look into it further.

**Comment by dannycabrera** [comment]
Thanks @ruddfawcett

**Comment by ruddfawcett** [comment]
Looking into this now, it looks like the `[result lockFocusFlipped:image.isFlipped]` ([referenced here](https://github.com/glyphish/color-changer/blob/development/Glyphish%20Color%20Changer/classes/NSImage%2BImageMask.m#L32)) is causing the issue - http://stackoverflow.com/a/17510651.

Trying to find a fix now.
